package de.fitcontrol.model.enums;

import com.fasterxml.jackson.databind.annotation.JsonDeserialize;

import de.fitcontrol.model.enums.deserializer.MusclegroupDeserializer;


@JsonDeserialize(using = MusclegroupDeserializer.class)
public enum MuscleGroup {
	
	Adductors,
	Adductor_Brevis,
	Adductor_Longus,
	Adductor_Magnus,
	Biceps_Brachii,
	Biceps_Femoris,
	Brachialis,
	Brachioradialis,
	Buccinator,
	Coracobrachialis,
	Deltoid,
	Digastric,
	Erector_Spinae,
	Extensor_Carpi_Radialis_Brevis,
	Extensor_Carpi_Radialis_Longus,
	Extensor_Carpi_Ulnaris,
	Extensor_Digitorum,
	External_Oblique,
	Flexor_Carpi_Radialis,
	Flexor_Carpi_Ulnaris,
	Flexor_Digitorum_Profundus,
	Flexor_Digitorum_Superficialis,
	Forearm_Extensors,
	Forearm_Flexors,
	Gastrocnemius,
	Gluteus_Maximus,
	Gluteus_Medius,
	Gluteus_Minimus,
	Gracilis,
	Hamstrings,
	Iliocostalis,
	Infraspinatus,
	Internal_Oblique,
	Latissimus_Dorsi,
	Levator_Scapulae,
	Longissimus,
	Masseter,
	Mylohyoid,
	Omohyoid,
	Palmaris_Longus,
	Pectineus,
	Pectoralis_Major,
	Pectoralis_Minor,
	Peroneus_Brevis,
	Peroneus_Longus,
	Platysma,
	Quadratus_Lumborum,
	Quadriceps,
	Rectus_Abdominis,
	Rectus_Femoris,
	Rhomboid_Major,
	Rhomboid_Minor,
	Semimembranosus,
	Semitendinosus,
	Serratus_Anterior,
	Soleus,
	Spinalis,
	Sternohyoid,
	Sternothyroid,
	Stylohyoid,
	Subscapularis,
	Supraspinatus,
	Temporalis,
	Tensor_Fasciae_Latae,
	Teres_Major,
	Teres_Minor,
	Thyrohyoid,
	Tibialis_Anterior,
	Tibialis_Posterior,
	Trapezius,
	Triceps_Brachii,
	Transversus_Abdominis,
	Vastus_Intermedius,
	Vastus_Lateralis,
	Vastus_Medialis
	
	/*
	 Trapezius ,
	 Deltoid ,
	 PectoralisMajor ,
	 PectoralisMinor ,
	 LatissimusDorsi ,
	 RhomboidMajor ,
	 RhomboidMinor ,
	 BicepsBrachii ,
	 Brachialis ,
	 Brachioradialis ,
	 TricepsBrachii ,
	 ForearmFlexors ,
	 ForearmExtensors ,
	 FlexorCarpiRadialis ,
	 FlexorCarpiUlnaris ,
	 PalmarisLongus ,
	 FlexorDigitorumSuperficialis ,
	 FlexorDigitorumProfundus ,
	 ExtensorCarpiRadialisLongus ,
	 ExtensorCarpiRadialisBrevis ,
	 ExtensorCarpiUlnaris ,
	 ExtensorDigitorum ,
	 RectusAbdominis ,
	 ExternalOblique ,
	 InternalOblique ,
	 TransversusAbdominis ,
	 ErectorSpinae ,
	 Iliocostalis ,
	 Longissimus ,
	 Spinalis ,
	 QuadratusLumborum ,
	 GluteusMaximus ,
	 GluteusMedius ,
	 GluteusMinimus ,
	 TensorFasciaeLatae ,
	 Quadriceps ,
	 RectusFemoris ,
	 VastusLateralis ,
	 VastusMedialis ,
	 VastusIntermedius ,
	 Hamstrings ,
	 BicepsFemoris ,
	 Semitendinosus ,
	 Semimembranosus ,
	 Adductors ,
	 AdductorLongus ,
	 AdductorBrevis ,
	 AdductorMagnus ,
	 Gracilis ,
	 Pectineus ,
	 Gastrocnemius ,
	 Soleus ,
	 TibialisAnterior ,
	 TibialisPosterior ,
	 PeroneusLongus ,
	 PeroneusBrevis ,
	 SerratusAnterior ,
	 Infraspinatus ,
	 Supraspinatus ,
	 TeresMajor ,
	 TeresMinor ,
	 LevatorScapulae ,
	 Subscapularis ,
	 Coracobrachialis ,
	 Platysma ,
	 Buccinator ,
	 Masseter ,
	 Temporalis ,
	 Digastric ,
	 Mylohyoid ,
	 Stylohyoid ,
	 Omohyoid ,
	 Sternohyoid ,
	 Sternothyroid ,
	 Thyrohyoid ,
*/

}

